tools:
  external_code_coverage:
    timeout: 1200
  php_code_coverage:
    enabled: false
  php_analyzer:
    enabled: true
    filter:
      paths: ["classes/*", "test/classes/*"]
  sensiolabs_security_checker: true

checks:
  php:
    duplication: false

build:
  tests: false
  nodes:
    analysis:
      tests:
        override:
          - 'php-scrutinizer-run --enable-security-analysis'
