sudo: false

addons:
  apt:
    packages:
    - python-docutils

language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
  allow_failures:
    - php: 5.2
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

script: ./.travis.sh

notifications:
  slack: phing:VFLtGWQdtJTgyPldJqwv5ZdH
