language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
 
matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0

script: ./.travis.sh

notifications:
  irc: "chat.freenode.net#phing"
