language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
 
matrix:
    allow_failures:
        - php:
            - 7.0
            - hhvm-nightly

script: ./.travis.sh

notifications:
  irc: "chat.freenode.net#phing"
