sudo: false

addons:
  apt:
    packages:
    - python-docutils

language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
 
matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

script: ./.travis.sh

notifications:
  irc: "chat.freenode.net#phing"
